parameters:
#    pixy_pixy.example.class: Pixy\PixyBundle\Example

services:
#    pixy_pixy.example:
#        class: %pixy_pixy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pixy_pixy.